version: '3'

services:
  postgres:
    image: "postgres:12.2"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: spaceSlackSync
      POSTGRES_DB: spaceSlackSync
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d spaceSlackSync -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
